#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 15 17:06:22 2017

@author: mi.zhang

appending one-day data each day
"""
import pdb
import os
import sys
import pandas as pd
import genKPI as gk
import time
### Change the datapath to the path the file is in
datapath = os.path.join("C:", "QlikDataFiles", "anab-1072")
kpifile = os.path.join(datapath, 'Canada_KPI_reporting_queries.xlsx')
thedate = str(pd.to_datetime(time.strftime("%Y-%m-%d")) - pd.Timedelta('1 days'))
outfile = os.path.join(datapath,'cumulative_daily_report.xlsx')


replacedate = '2016-12-20'

sys.path.append(datapath)

kpi = gk.genKPI('RS')

def genKPIforSheet(sheetname, withgroup, groupname):
    querydf = pd.read_excel(kpifile,sheetname = sheetname)
    if withgroup:
        result = kpi.genKPIWithGroup(querydf,'Query','KPI name',groupname, thedate, thedate, replacedate)
    else:
        result = kpi.genKPINoGroup(querydf,'Query','KPI name', thedate, thedate, replacedate)
    return result
     
#without group, append new data to cumulative_daily_report
writer = pd.ExcelWriter(outfile)
sheetlist = ['Basic KPI', 'User Status of MAU', 'Response of Card Registration', 'Membership KPI']
for sheetname in sheetlist:
    print (sheetname)
    pre_result = pd.read_excel(outfile,sheetname = sheetname)
    result = genKPIforSheet(sheetname, False, '')    
    result = pd.concat([pre_result,result])
    result.to_excel(writer, sheet_name=sheetname)
writer.save()


#with group, generate a file for daily data
sheetlist = ['KPI by app version', 'KPI by device model', 'KPI by card name', 'Membership by card name']
grouplist = ['app_ver', 'device_model', 'card_name', 'card_name']
for i in list(range(0, 4)):
    result = genKPIforSheet(sheetlist[i], True, grouplist[i])
    writer = pd.ExcelWriter(os.path.join(datapath,thedate+'_'+sheetlist[i]+'.xlsx')
    result.to_excel(writer, sheet_name=sheetlist[i])
    writer.save()
